# Generated by Django 4.1.7 on 2023-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
