# Generated by Django 4.1.7 on 2023-02-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_feature_details_alter_feature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('password2', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
